### PR TITLE
Release 6.1.4

### PR DESCRIPTION
**Pull request by Costya-Y**
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/cloudshell-networking-cisco/134)

### CODE REVIEW

**Review by yaroslavNqualisystems — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualisystems/cloudshell-networking-cisco/134)* status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @Costya-Y)

___
*[cloudshell/networking/cisco/command_actions/add_remove_vlan_actions.py, line 65 at r5](https://reviewable.io/reviews/qualisystems/cloudshell-networking-cisco/134#-MdHM9Sy95QUn2ZlyYtp:-MdHM9Sy95QUn2ZlyYtq:b-t5c7l5) ([raw file](https://github.com/qualisystems/cloudshell-networking-cisco/blob/b614c88377e83561db9e4ddfb38fd93ad7231eb9/cloudshell/networking/cisco/command_actions/add_remove_vlan_actions.py#L65)):*
> ```Python
>             str_vlan_range_ls = vlan_range.split("-")
> 
>             vlan_range_ls = list(map(int, str_vlan_range_ls))
> ```

Looks like transformation to list could be ommited

**Comment by Costya-Y** [comment]
___
*[cloudshell/networking/cisco/command_actions/add_remove_vlan_actions.py, line 65 at r5](https://reviewable.io/reviews/qualisystems/cloudshell-networking-cisco/134#-MdHM9Sy95QUn2ZlyYtp:-MdHPnge7hnhEuToQ6Xh:blh5pjs) ([raw file](https://github.com/qualisystems/cloudshell-networking-cisco/blob/b614c88377e83561db9e4ddfb38fd93ad7231eb9/cloudshell/networking/cisco/command_actions/add_remove_vlan_actions.py#L65)):*
<details><summary><i>Previously, yaroslavNqualisystems (Yaroslav Nikonorov) wrote…</i></summary><blockquote>

Looks like transformation to list could be ommited
</blockquote></details>

Not really, map function in py 3 returns an iterator, not a list. In my case, I need a list since later I'm calling min/max functions.

**Comment by yaroslavNqualisystems** [comment]
min/max can use iterator as input

**Review by yaroslavNqualisystems — COMMENTED** [review]
> Reviewed 20 of 20 files at r5.
> *[Reviewable](https://reviewable.io/reviews/qualisystems/cloudshell-networking-cisco/134)* status: all files reviewed, 1 unresolved discussion (waiting on @yaroslavNqualisystems)

**Review by yaroslavNqualisystems — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualisystems/cloudshell-networking-cisco/134)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Costya-Y)

**Pull request merged**
